export const SET_APP_INFO_DATA = 'SET_APP_INFO_DATA';
export const SET_APP_INFO_PENDING = 'SET_APP_INFO_PENDING';
export const SET_APP_INFO_REJECTED = 'SET_APP_INFO_REJECTED';
export const SET_URL = 'SET_URL';
export const SET_CONTENT_LIST = 'SET_CONTENT_LIST';
export const DELETE_CONTENT_FROM_LIST = 'DELETE_CONTENT_FROM_LIST';
export const CLEAN_CONTENT = 'CLEAN_CONTENT';