export const SET_PROPERTIES_INFO_DATA = 'SET_PROPERTIES_INFO_DATA';
export const SET_PROPERTIES_INFO_PENDING = 'SET_PROPERTIES_INFO_PENDING';
export const SET_PROPERTIES_INFO_REJECTED = 'SET_PROPERTIES_INFO_REJECTED';